apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: roboshop
spec:
  selector:
    project: roboshop
    component: redis
    tier: db
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} # service port
      targetPort: 6379 # container port