deployment:
  replicas: 1
  imageRepo: kirankumarkosuri/user
  imageVersion: v1
  configMap:
    redisURL: "redis://redis:6379"
    mongoURL: "mongodb://mongodb:27017/users"
    

service:
  servicePort: "8080"